#!/usr/bin/env node
/**
 * Step 6 — build the client-side dataset (incremental).
 *
 * Reads data/all_bugs_enriched.json (summary + linked commands per bug) and
 * data/all_bugs_context.json (versions per bug), joins them by `reference`,
 * and writes the two files the browser actually loads:
 *
 *   docs/data/meta.json       [{ reference, summary, commands, versions }]
 *   docs/data/embeddings.bin  raw Float32Array, row-major [N x 384], L2-normalized
 *
 * plus docs/src/beta-versions.js, the generated list of versions that only
 * exist as a bugs.4d.com *beta branch* (?branch=…) and have no released
 * listing (?version=… returns the error page), so version links point
 * somewhere real.
 *
 * Incremental: a bug whose `summary` is byte-identical to the one in the
 * existing meta.json keeps its existing embedding row, copied straight across.
 * Only new or rewritten summaries are actually run through the model, so a
 * routine update embeds a hundred bugs instead of two and a half thousand.
 * Pass --force to re-embed everything (e.g. after a model change).
 *
 * --lang ja builds the Japanese site's dataset instead: summaries come from
 * data/all_bugs_ja.json (commands and versions are shared with English), are
 * embedded with the Japanese ruri-v3-30m model, and land in docs/data/ja/.
 * Every bug must have a translation (see merge_translation.py).
 *
 * The model settings per language must match docs/src/i18n.js exactly, or
 * query and corpus vectors stop being comparable.
 *
 * Run from scripts/: `npm install && node update/generate_embeddings.mjs [--lang ja]`
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const BATCH_SIZE = 32;

const langArg = process.argv.indexOf("--lang");
const LANG = langArg >= 0 ? process.argv[langArg + 1] : "en";

const LANGS = {
  en: {
    library: "@xenova/transformers",
    model: "Xenova/all-MiniLM-L6-v2",
    options: { quantized: true },
    dim: 384,
    docPrefix: "",
    outDir: path.join(REPO_ROOT, "docs", "data"),
  },
  ja: {
    library: "@huggingface/transformers",
    model: "sirasagi62/ruri-v3-30m-ONNX",
    options: { dtype: "q8", revision: "cdf9391f1ff2198daa8f63f7ccf97d7b3e7415a0" },
    dim: 256,
    docPrefix: "検索文書: ",
    outDir: path.join(REPO_ROOT, "docs", "data", "ja"),
    summaries: path.join(REPO_ROOT, "data", "all_bugs_ja.json"),
  },
};
const CONFIG = LANGS[LANG];
if (!CONFIG) {
  console.error(`Unknown --lang ${LANG}; expected one of ${Object.keys(LANGS).join(", ")}`);
  process.exit(2);
}
const EMBED_DIM = CONFIG.dim;

const ENRICHED_PATH = path.join(REPO_ROOT, "data", "all_bugs_enriched.json");
const CONTEXT_PATH = path.join(REPO_ROOT, "data", "all_bugs_context.json");
const STATE_PATH = path.join(REPO_ROOT, "data", "update_state.json");
const OUT_DIR = CONFIG.outDir;
const OUT_BIN = path.join(OUT_DIR, "embeddings.bin");
const OUT_META = path.join(OUT_DIR, "meta.json");
const OUT_BETA = path.join(REPO_ROOT, "docs", "src", "beta-versions.js");

const FORCE = process.argv.includes("--force");

/** Strip markdown link syntax `[text](url)` down to just `text`, so the
 * embedding model sees clean prose instead of URLs/markdown noise. This must
 * stay identical to the client's `stripLinks`, or query and corpus vectors
 * stop being comparable. */
function stripMarkdownLinks(text) {
  return text.replace(/\[([^\]]+)\]\(([^)]+)\)/g, "$1");
}

async function readJson(file, fallback) {
  try {
    return JSON.parse(await readFile(file, "utf8"));
  } catch (err) {
    if (err.code === "ENOENT" && fallback !== undefined) return fallback;
    throw err;
  }
}

async function readExistingEmbeddings(meta) {
  if (!meta.length) return null;
  try {
    const buf = await readFile(OUT_BIN);
    const expected = meta.length * EMBED_DIM * 4;
    if (buf.byteLength !== expected) {
      console.warn(
        `Existing ${LANG} embeddings.bin is ${buf.byteLength} bytes but meta.json implies ${expected}; re-embedding everything.`
      );
      return null;
    }
    return new Float32Array(buf.buffer, buf.byteOffset, meta.length * EMBED_DIM);
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw err;
  }
}

async function writeBetaVersions(versions) {
  const body = `// Generated by scripts/update/generate_embeddings.mjs — do not edit by hand.
// Versions bugs.4d.com only publishes as a beta branch: for these,
// ?version=<v> returns the error page and ?branch=<v> is the real listing.
export const BETA_ONLY_VERSIONS = new Set(${JSON.stringify(versions)});
`;
  await writeFile(OUT_BETA, body);
  return versions;
}

async function main() {
  console.log("Loading dataset...");
  const enriched = await readJson(ENRICHED_PATH);
  const context = await readJson(CONTEXT_PATH);
  const state = await readJson(STATE_PATH, {});

  const versionsByRef = new Map(context.map((c) => [c.reference, c.versions ?? []]));

  let summaryByRef = null;
  if (CONFIG.summaries) {
    const translated = await readJson(CONFIG.summaries, []);
    summaryByRef = new Map(translated.map((t) => [t.reference, t.summary]));
    const missing = enriched.filter((bug) => !summaryByRef.has(bug.reference));
    if (missing.length) {
      throw new Error(
        `${missing.length} bug(s) have no ${LANG} summary (e.g. ${missing
          .slice(0, 5)
          .map((b) => b.reference)
          .join(", ")}); run build_translation.py and merge the translations first.`
      );
    }
  }

  const records = enriched.map((bug) => ({
    reference: bug.reference,
    summary: summaryByRef ? summaryByRef.get(bug.reference) : bug.summary,
    commands: bug.commands ?? [],
    versions: versionsByRef.get(bug.reference) ?? [],
  }));

  const missingVersions = records.filter((r) => r.versions.length === 0);
  if (missingVersions.length) {
    console.warn(
      `Warning: ${missingVersions.length} bug(s) have no versions, e.g. ${missingVersions
        .slice(0, 5)
        .map((r) => r.reference)
        .join(", ")}`
    );
  }

  const previousMeta = FORCE ? [] : await readJson(OUT_META, []);
  const previousEmbeddings = FORCE ? null : await readExistingEmbeddings(previousMeta);
  const previousRows = new Map();
  if (previousEmbeddings) {
    previousMeta.forEach((rec, i) => previousRows.set(rec.reference, { row: i, summary: rec.summary }));
  }

  const floatArray = new Float32Array(records.length * EMBED_DIM);
  const toEmbed = [];
  let reused = 0;
  records.forEach((record, i) => {
    const previous = previousRows.get(record.reference);
    if (previous && previous.summary === record.summary) {
      floatArray.set(
        previousEmbeddings.subarray(previous.row * EMBED_DIM, (previous.row + 1) * EMBED_DIM),
        i * EMBED_DIM
      );
      reused += 1;
    } else {
      toEmbed.push(i);
    }
  });

  console.log(`${records.length} bugs: reusing ${reused} embeddings, computing ${toEmbed.length}.`);

  if (toEmbed.length) {
    console.log(`Loading embedding model ${CONFIG.model}...`);
    const { pipeline } = await import(CONFIG.library);
    const embedder = await pipeline("feature-extraction", CONFIG.model, CONFIG.options);
    for (let start = 0; start < toEmbed.length; start += BATCH_SIZE) {
      const slice = toEmbed.slice(start, start + BATCH_SIZE);
      const texts = slice.map((i) => CONFIG.docPrefix + stripMarkdownLinks(records[i].summary));
      const output = await embedder(texts, { pooling: "mean", normalize: true });
      slice.forEach((recordIndex, j) => {
        floatArray.set(
          output.data.subarray(j * EMBED_DIM, (j + 1) * EMBED_DIM),
          recordIndex * EMBED_DIM
        );
      });
      process.stdout.write(`\r  ${Math.min(start + BATCH_SIZE, toEmbed.length)}/${toEmbed.length}`);
    }
    console.log("\nDone embedding.");
  }

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_BIN, Buffer.from(floatArray.buffer));
  await writeFile(OUT_META, JSON.stringify(records));
  console.log(`Wrote ${OUT_BIN} (${floatArray.byteLength} bytes)`);
  console.log(`Wrote ${OUT_META} (${records.length} records)`);

  if (LANG === "en") {
    const beta = await writeBetaVersions(state.beta_only_versions ?? []);
    console.log(`Wrote ${OUT_BETA} (${beta.length} beta-only versions: ${beta.join(", ") || "none"})`);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
